In [88]:
import cv2 as cv
import numpy as np
import pandas as pd 
import sklearn.metrics.pairwise as pairwise
import vptree
from sklearn import preprocessing 
import pickle

In [4]:
import import_ipynb
import ActionClassificationCosineDatasetGen as Dataset

In [61]:
ARGS = {'TREE':None,
       'X': Dataset.read_dataset(norm=True).loc[:,data.columns != 'label'],
       'Y': Dataset.read_dataset(norm=True).loc[:,data.columns == 'label'],
       'TREEPATH':'/Users/sandeep/Desktop/dataandmodles/models/vptrees'}


In [36]:
data = Dataset.read_dataset(norm=True)
data.head()

0_x       0_y       1_x       1_y       2_x       2_y       3_x  \
0  0.216458  0.032754  0.175160  0.062659  0.162344  0.068355  0.143831   
1  0.220442  0.037707  0.187086  0.059461  0.168232  0.060912  0.146478   
2  0.205067  0.024941  0.196753  0.047110  0.181512  0.056809  0.152415   
3  0.208959  0.030808  0.188867  0.056258  0.172793  0.060277  0.150022   
4  0.217482  0.039419  0.188937  0.065244  0.193015  0.066604  0.157674   

        3_y       4_x       4_y  ...      13_y      14_x      14_y      15_x  \
0  0.129590  0.159495  0.175160  ...  0.313295  0.210762  0.027057  0.216458   
1  0.131975  0.162431  0.185636  ...  0.192887  0.217542  0.029006  0.220442   
2  0.124703  0.149643  0.160728  ...  0.310371  0.205067  0.024941  0.205067   
3  0.113856  0.150022  0.164756  ...  0.290668  0.208959  0.030808  0.208959   
4  0.118256  0.152237  0.156315  ...  0.293600  0.217482  0.039419  0.217482   

       15_y      16_x      16_y      17_x      17_y  label  
0  0.032754  0.197945  0.027057  0.216458  0.032754   walk  
1  0.037707  0.192887  0.031906  0.220442  0.037707   walk  
2  0.024941  0.205067  0.024941  0.205067  0.024941   walk  
3  0.030808  0.208959  0.030808  0.208959  0.030808   walk  
4  0.039419  0.217482  0.039419  0.183500  0.035341   walk  

[5 rows x 37 columns]

In [56]:
data.loc[:,data.columns != 'label']

0_x       0_y       1_x       1_y       2_x       2_y       3_x  \
0       0.216458  0.032754  0.175160  0.062659  0.162344  0.068355  0.143831   
1       0.220442  0.037707  0.187086  0.059461  0.168232  0.060912  0.146478   
2       0.205067  0.024941  0.196753  0.047110  0.181512  0.056809  0.152415   
3       0.208959  0.030808  0.188867  0.056258  0.172793  0.060277  0.150022   
4       0.217482  0.039419  0.188937  0.065244  0.193015  0.066604  0.157674   
...          ...       ...       ...       ...       ...       ...       ...   
593355  0.178816  0.043614  0.171547  0.074143  0.206438  0.068328  0.232606   
593356  0.175648  0.043192  0.172769  0.074866  0.207322  0.069107  0.221720   
593357  0.173691  0.049412  0.164707  0.080856  0.205135  0.073369  0.256044   
593358  0.165712  0.075588  0.165712  0.075588  0.202053  0.069774  0.251476   
593359  0.165301  0.049300  0.159501  0.089900  0.198651  0.085550  0.247951   

             3_y       4_x       4_y  ...      13_x      13_y      14_x  \
0       0.129590  0.159495  0.175160  ...  0.126742  0.313295  0.210762   
1       0.131975  0.162431  0.185636  ...  0.198688  0.192887  0.217542   
2       0.124703  0.149643  0.160728  ...  0.128860  0.310371  0.205067   
3       0.113856  0.150022  0.164756  ...  0.172793  0.290668  0.208959   
4       0.118256  0.152237  0.156315  ...  0.193015  0.293600  0.217482   
...          ...       ...       ...  ...       ...       ...       ...   
593355  0.047975  0.232606  0.047975  ...  0.135202  0.308203  0.178816   
593356  0.110860  0.224599  0.139655  ...  0.136775  0.305225  0.175648   
593357  0.061391  0.208129  0.062888  ...  0.139252  0.312943  0.173691   
593358  0.069774  0.248568  0.055237  ...  0.141001  0.303806  0.165712   
593359  0.104400  0.239251  0.089900  ...  0.134851  0.303051  0.156601   

            14_y      15_x      15_y      16_x      16_y      17_x      17_y  
0       0.027057  0.216458  0.032754  0.197945  0.027057  0.216458  0.032754  
1       0.029006  0.220442  0.037707  0.192887  0.031906  0.220442  0.037707  
2       0.024941  0.205067  0.024941  0.205067  0.024941  0.205067  0.024941  
3       0.030808  0.208959  0.030808  0.208959  0.030808  0.208959  0.030808  
4       0.039419  0.217482  0.039419  0.217482  0.039419  0.183500  0.035341  
...          ...       ...       ...       ...       ...       ...       ...  
593355  0.043614  0.178816  0.043614  0.178816  0.043614  0.148287  0.049429  
593356  0.043192  0.175648  0.043192  0.175648  0.043192  0.145414  0.048951  
593357  0.049412  0.173691  0.049412  0.173691  0.049412  0.139252  0.055401  
593358  0.075588  0.165712  0.075588  0.165712  0.075588  0.138094  0.047969  
593359  0.047850  0.165301  0.049300  0.153701  0.053650  0.134851  0.060900  

[593360 rows x 36 columns]

In [69]:
def cosineDistanceMatching(poseVector1,poseVector2):
    '''
    Returns the cosine similarity as a distance function between the two L2 normalized vectors.
    The distance is inversely porportional to the similarity between the two vectors
    '''
    poseVector1 , poseVector2 = np.array(poseVector1).reshape(1,-1) , np.array(poseVector2).reshape(1,-1)
    cosineDistance = pairwise.cosine_distances(poseVector1 , poseVector2) 
    distance = np.sqrt(cosineDistance * 2)
    return distance

    

In [64]:
def getPoseData():
    '''
    Helper function of buildVPTree()
    '''
    return ARGS['X'].values.tolist()

In [45]:
def buildVPTree():
    poseData = getPoseData()
    ARGS['TREE'] = vptree.VPTree(poseData,cosineDistanceMatching)


In [77]:
def l2Normalize(poses):
    '''
    Helper function of findMatch()
    PARAM poses: a list containing pose [....]
    '''
    return preprocessing.normalize([poses], axis=1)[0]

In [32]:
preprocessing.normalize([[1,1,2,3,4]], axis=1)

array([[0.1796053 , 0.1796053 , 0.3592106 , 0.53881591, 0.71842121]])

In [75]:
def findMatch(pose):
    pose = l2Normalize(pose)
    similarPoses= ARGS['TREE'].get_n_nearest_neighbors(pose, 10)
    return similarPoses

In [94]:
def saveTree(fileName):
    '''
    Save the tree to the path defined at  ARGS['TREEPATH']
    Parameters
    -----------
    fileName : The file name of the plk file
    '''
    
    file_vptree = f"{ARGS['TREEPATH']}/{fileName}.pkl"
    with open(file_vptree, 'wb') as output:
        pickle.dump(ARGS['TREE'], output, pickle.HIGHEST_PROTOCOL)

In [96]:
def loadTree(fileName):
    file_vptree = f"{ARGS['TREEPATH']}/{fileName}.pkl"
    with open(file_vptree, 'rb') as input:
        ARGS['TREE'] = pickle.load(input) 

In [70]:
buildVPTree()

In [85]:
pose = ARGS['X'].iloc[1].values.tolist()
similarPoses = findMatch(pose);similarPoses

[(array([[0.]]),
  array([0.22044224, 0.03770723, 0.18708585, 0.05946139, 0.16823224,
         0.06091167, 0.14647807, 0.13197529, 0.16243112, 0.18563557,
         0.19868807, 0.05801112, 0.19868807, 0.05801112, 0.19868807,
         0.05801112, 0.14647807, 0.15808029, 0.16533168, 0.24654724,
         0.12617418, 0.32051142, 0.18708585, 0.15227918, 0.19868807,
         0.19288696, 0.19868807, 0.19288696, 0.21754168, 0.02900556,
         0.22044224, 0.03770723, 0.19288696, 0.03190611, 0.22044224,
         0.03770723])),
 (array([[0.]]),
  array([0.22044224, 0.03770723, 0.18708585, 0.05946139, 0.16823224,
         0.06091167, 0.14647807, 0.13197529, 0.16243112, 0.18563557,
         0.19868807, 0.05801112, 0.19868807, 0.05801112, 0.19868807,
         0.05801112, 0.14647807, 0.15808029, 0.16533168, 0.24654724,
         0.12617418, 0.32051142, 0.18708585, 0.15227918, 0.19868807,
         0.19288696, 0.19868807, 0.19288696, 0.21754168, 0.02900556,
         0.22044224, 0.03770723, 0.19288696, 