In [1]:
import cv2 as cv
import numpy as np
import pandas as pd 
import sklearn.metrics.pairwise as pairwise
import vptree
from sklearn import preprocessing 
import pickle

In [2]:
import import_ipynb
import ActionClassificationCosineDatasetGen as Dataset

importing Jupyter notebook from ActionClassificationCosineDatasetGen.ipynb


In [10]:
data = Dataset.read_dataset(norm=True)
ARGS = {'TREE':None,
       'X': Dataset.read_dataset(norm=True).loc[:,data.columns != 'label'],
       'Y': Dataset.read_dataset(norm=True).loc[:,data.columns == 'label'] }


In [5]:
def cosineDistanceMatching(poseVector1,poseVector2):
    '''
    Returns the cosine similarity as a distance function between the two L2 normalized vectors.
    The distance is inversely porportional to the similarity between the two vectors
    '''
    poseVector1 , poseVector2 = np.array(poseVector1).reshape(1,-1) , np.array(poseVector2).reshape(1,-1)
    cosineDistance = pairwise.cosine_distances(poseVector1 , poseVector2) 
    distance = np.sqrt(cosineDistance * 2)
    return distance

In [14]:
def l2Normalize(poses):
    '''
    Helper function of findMatch()
    PARAM poses: a list containing pose [....]
    '''
    return preprocessing.normalize([poses], axis=1)[0]

In [11]:
def findMatch(pose):
    pose = l2Normalize(pose)
    similarPoses= ARGS['TREE'].get_n_nearest_neighbors(pose, 10)
    return similarPoses

In [12]:
file_vptree = '/Users/sandeep/Desktop/dataandmodles/models/vptrees/vptreeCosineDistance.pkl'
with open(file_vptree, 'rb') as input:
    ARGS['TREE'] = pickle.load(input)

In [15]:
pose = ARGS['X'].iloc[1].values.tolist()
similarPoses = findMatch(pose);similarPoses

[(array([[0.]]),
  array([0.22044224, 0.03770723, 0.18708585, 0.05946139, 0.16823224,
         0.06091167, 0.14647807, 0.13197529, 0.16243112, 0.18563557,
         0.19868807, 0.05801112, 0.19868807, 0.05801112, 0.19868807,
         0.05801112, 0.14647807, 0.15808029, 0.16533168, 0.24654724,
         0.12617418, 0.32051142, 0.18708585, 0.15227918, 0.19868807,
         0.19288696, 0.19868807, 0.19288696, 0.21754168, 0.02900556,
         0.22044224, 0.03770723, 0.19288696, 0.03190611, 0.22044224,
         0.03770723])),
 (array([[0.]]),
  array([0.22044224, 0.03770723, 0.18708585, 0.05946139, 0.16823224,
         0.06091167, 0.14647807, 0.13197529, 0.16243112, 0.18563557,
         0.19868807, 0.05801112, 0.19868807, 0.05801112, 0.19868807,
         0.05801112, 0.14647807, 0.15808029, 0.16533168, 0.24654724,
         0.12617418, 0.32051142, 0.18708585, 0.15227918, 0.19868807,
         0.19288696, 0.19868807, 0.19288696, 0.21754168, 0.02900556,
         0.22044224, 0.03770723, 0.19288696, 